---
title: "Exploratory Data Analysis"
author: "Nathan Young"
output: pdf_document
---
In this document, I'm taking notes based off the Coursera course Exploratory Data Analysis. 

## Week 1
### Setting Your Working Directory (Windows)
To find current working directory: getwd().

The working directory is where R finds all of its files for reading and writing on your computer. When you read data or write things out using functions or write.csv, they will be read or written to your home, your working directory. 

To find files in current working directory: dir()

It is a good idea when working on a class or project to create a folder that you store everything in for the project and set this folder as the working directory. 

To find what is in workspace: ls()

If a R file is saved in the working directory (visible when running dir()), you can source it to load its contents to the workspace with source("filename")

### Principles of Analytic Graphics
Based on book by Edward Tuffey, Beautiful Evidence, with the following principles. 

1. Show Comparisons
  + Evidence for a hypothesis is always *relative* to another competing hypothesis
  + Always ask "compared to what?" Evidence is relative

In boxplot example of an air cleaner vs change in asthma symptom free days, what are we comparing to? We need to compare to a control (or something eise) so we can see the impact of the treatment. 

2. Show causality, mechanism, explanation, systematic structure. 
  + What is your causal framework for thinking about a question? 

In prior example of air cleaner and asthma days, what improves their symptoms? Hypothesize that air cleaner is removing particulate matter and improving symptoms. So we might also show a plot of fine particulate matter in control vs air cleaner. This allows us to say that not only do symptoms decrease but the air is cleaner linking the particulate matter and symptoms.  

3. Show multivariate data
  + multivariate means more than two variables. 
  + The real world is multivariate
  + Need to "escape flatland"

This rule boils down to show as much data on a single plot as you can. And the reason is because the world is inherently multivariate, including more information on a plot better mirrors the world. 

Example plot of concentration of particulate matter vs daily mortality in NYC from 1987 till 2000. Overall slight negative association between PM10 levels and mortality. Regression line slopes downward slightly. Could hypothesize that lower airpollution is associated with higher mortality but if you include additional confounding variables such as season it can change the picture. When broken down to each season, there is now a slight positive correlation (simpson's paradox)

4. Integration of evidence
  + Completely integrate words, numbers, images, and diagrams
  + Data graphics should make use of many modes of data presentation
  + Don't let hte tool drive the analysis

Use as many different modes of evidence or displaying evidence as you can. Don't show only a plot, or a table, but use multiple to make the information as rich as possible. Advantage of R, use flexible tools. 

5. Describe and document the evidence with appropriate labels, scales, sources, etc. 
  + A data graphic should tell a complete story that is credible. 

Preserve the code that made the plot and the souces of where you got the data to maintain the credibility. 

6. Content is king
  + Analytical presentation ultimately stand or fall depending on the quality, relevance, and integrity of their content. 

What's the story, what's the data, whats the best way to present it? 
